import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx,json}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx,json}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx,json}',
  ],
  theme: {
    extend: {
      dropShadow: {
        '3xl': '-1px 1px 10px rgba(98, 98, 98, 0.15)',
        custom: '5px 5px 18.1px 0 rgba(167, 255, 171, 0.07)',
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        'custom-blue': '#11998E',
        'custom-green': '#38EF7D',
        'custom-second-green': '#C2FAD7',
        'custom-background': '#1b3431',
        'custom-running-first': '#A1FFCE',
        'custom-running-second': '#FAFFD1',
        'custom-black': '#333333',
        'custom-yellow': '#6B662E',
        'custom-blue-second': '#5B86E5',
        'custom-blue-third': '#36D1DC',
        'custom-grey': '#434343',
        'custom-button': '#15645E',
        'custom-form': '#F4F4F6',
        'custom-hover-first': '#00F260',
        'custom-hover-second': '#0575E6',
        'custom-case-btn': '#2C5364',
        'custom-case-modal': '#161616',
        'custom-team': '#3E3E3E',
        'custom-player-one': '#41D77C',
        'custom-player-two': '#227141',
        'custom-opacity-one': 'rgb(0,0,0/ .3)',
        'custom-opacity-two': 'rgb(0,0,0)',
      },
      backgroundImage: {
        texture: "url('/background.png')",
        form: "url('/footer-form-bkg.jpg')",
        contactUsModal: "url('/doodad.jpg')",
        bkgForm: "url('/bkg-form.jpg')",
        test: "url('/contact-us-form.jpg')",
        woodMinded: "url('/wood-minded.jpg')",
        alcotrade: "url('/alcotrade.jpg')",
        inside: "url('/inside.jpg')",
        yourProject: "url('/your-project.jpg')",
        woodImage: "url('/wood-site.jpg')",
        alcotradeImage: "url('/alcotrade-site.jpg')",
        insideImage: "url('/inside-site.jpg')",
        siteImage: "url('/bg-solution-website.jpg')",
        whoAreWe: "url('/who.jpg')",
        stack: "url('/bg-stack.jpg')",
        dash: "url(\"data:image/svg+xml, %3csvg width='256' height='256' viewBox='0 0 256 256' fill='none' xmlns='http://www.w3.org/2000/svg'%3e %3ccircle cx='128' cy='128' r='128' stroke='white' stroke-dasharray='13 13'/%3e %3c/svg%3e\");\n",
        ecommerceExpertise: "url('/wood-expertise.jpg')",
      },
    },
  },
  plugins: [],
};
export default config;
